development:
  adapter: mysql
  encoding: utf8
  database: longitude_dev
  username: username
  password:

test:
  adapter: mysql
  encoding: utf8
  database: longitude_test
  username: username
  password:

production:
  adapter: mysql
  encoding: utf8
  database: longitude_prod
  username: username
  password:
